#\u7B2C\u4E8C\u6B65\uFF1A\u7136\u540E\u53BB\u5199\u914D\u7F6E\u6587\u4EF6
server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    配置security默认的用户名和密码，不然每次启动项目security的密码都会改变
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    header: Authorization
    expire: 604800   # 设置 7天过期
    secret: ji8n3439n439n43ld9ne9343fdfer49h  #密钥为32为随机数，用来加密解密使用